import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🍄 Seeding Shrooms database...')

  // ── SPECIES ───────────────────────────────────────────────────────────────
  const speciesData = [
    {
      slug: 'blue-oyster',
      commonName: 'Blue Oyster',
      scientificName: 'Pleurotus ostreatus',
      family: 'Pleurotaceae',
      order: 'Agaricales',
      type: 'edible',
      difficulty: 'beginner',
      substrate: ['hardwood sawdust', 'straw', 'coffee grounds'],
      colonizationWeeksMin: 2,
      colonizationWeeksMax: 3,
      fruitingTempFMin: 55,
      fruitingTempFMax: 65,
      fruitingTempCMin: 13,
      fruitingTempCMax: 18,
      expectedFlushes: 3,
      biologicalEfficiency: '25%',
      betaGlucanContent: 'High (25–30% dry weight)',
      indoorOutdoor: 'both',
      descriptionEn: 'The Blue Oyster mushroom is the most forgiving species for beginners. Native to temperate forests worldwide, Pleurotus ostreatus forms beautiful fan-shaped clusters with a blue-grey to cream coloring that deepens in cooler temperatures. It has a mild, slightly sweet flavor with a firm, meaty texture that works wonderfully across many cooking styles.',
      descriptionEs: 'El hongo Ostra Azul es la especie más indulgente para principiantes. Nativo de bosques templados de todo el mundo, el Pleurotus ostreatus forma hermosos racimos en forma de abanico con una coloración azul-gris a crema que se profundiza en temperaturas más frías. Tiene un sabor suave y ligeramente dulce con una textura firme y carnosa.',
      cultivationNotesEn: 'Blue Oysters thrive in a wide range of conditions. Pack your substrate into buckets or bags, inoculate with grain spawn, and wait 2–3 weeks for full colonization. Induce fruiting by introducing fresh air exchange and maintaining 85–95% humidity. Expect 3–4 flushes over 6–8 weeks.',
      cultivationNotesEs: 'Las Ostras Azules prosperan en una amplia gama de condiciones. Empaca el sustrato en cubetas o bolsas, inocula con spawn de grano y espera 2-3 semanas para la colonización completa. Induce la fructificación introduciendo intercambio de aire fresco y manteniendo 85-95% de humedad.',
      medicalNotesEn: 'Rich in beta-glucans, ergothioneine, and lovastatin. Studies suggest cholesterol-lowering effects, immune modulation, and anti-inflammatory properties. High in protein (30% dry weight) and contains all essential amino acids.',
      medicalNotesEs: 'Rico en beta-glucanos, ergotionina y lovastatina. Los estudios sugieren efectos reductores del colesterol, modulación inmune y propiedades antiinflamatorias. Alto en proteínas (30% peso seco) y contiene todos los aminoácidos esenciales.',
      cookingNotesEn: 'Excellent sautéed in butter with garlic, roasted in the oven, or used as a seafood substitute in tacos and stir-fries. The firm texture holds up well to high heat. Pairs beautifully with thyme, white wine, and cream.',
      cookingNotesEs: 'Excelente salteado en mantequilla con ajo, asado al horno o usado como sustituto de mariscos en tacos y salteados. La textura firme aguanta bien el calor alto. Combina perfecto con tomillo, vino blanco y crema.',
      lookalikes: [],
      imageUrl: 'https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=400',
    },
    {
      slug: 'lions-mane',
      commonName: "Lion's Mane",
      scientificName: 'Hericium erinaceus',
      family: 'Hericiaceae',
      order: 'Russulales',
      type: 'medicinal',
      difficulty: 'intermediate',
      substrate: ['hardwood sawdust'],
      colonizationWeeksMin: 3,
      colonizationWeeksMax: 4,
      fruitingTempFMin: 65,
      fruitingTempFMax: 75,
      fruitingTempCMin: 18,
      fruitingTempCMax: 24,
      expectedFlushes: 2,
      biologicalEfficiency: '15–20%',
      betaGlucanContent: 'Very High',
      indoorOutdoor: 'indoor',
      descriptionEn: "Lion's Mane is one of the most visually striking and scientifically fascinating mushrooms in existence. Its cascading white spines resemble a lion's mane, giving it an otherworldly appearance. Revered in Traditional Chinese Medicine for centuries, modern science has confirmed powerful neuroprotective and cognitive-enhancing properties.",
      descriptionEs: "La Melena de León es uno de los hongos más visualmente impactantes y científicamente fascinantes que existen. Sus espinas blancas en cascada se asemejan a la melena de un león, dándole una apariencia de otro mundo. Venerada en la medicina tradicional china durante siglos, la ciencia moderna ha confirmado poderosas propiedades neuroprotectoras.",
      cultivationNotesEn: "Lion's Mane requires high humidity (90–95%) and excellent fresh air exchange. It is sensitive to CO2 buildup, which causes it to form elongated, icicle-like growths instead of the classic pom-pom shape. Use enriched hardwood sawdust blocks and maintain 65–75°F during fruiting.",
      cultivationNotesEs: "La Melena de León requiere alta humedad (90-95%) y excelente intercambio de aire fresco. Es sensible a la acumulación de CO2, que la hace formar crecimientos elongados en forma de carámbano en lugar de la forma clásica de pompón.",
      medicalNotesEn: "Contains hericenones and erinacines — two unique compounds that stimulate Nerve Growth Factor (NGF) synthesis. Clinical studies show improvement in mild cognitive impairment, anxiety, depression, and neuropathic pain. Currently being researched for Alzheimer's and Parkinson's prevention.",
      medicalNotesEs: "Contiene hericenones y erinacinas — dos compuestos únicos que estimulan la síntesis del Factor de Crecimiento Nervioso (NGF). Estudios clínicos muestran mejoras en deterioro cognitivo leve, ansiedad, depresión y dolor neuropático.",
      cookingNotesEn: "Has a remarkable seafood-like texture and flavor — often compared to crab or lobster. Best sliced thick and seared in a very hot pan with butter. The key is extracting moisture first to achieve a golden crust. Superb in pasta, risotto, or simply on toast.",
      cookingNotesEs: "Tiene una textura y sabor notablemente parecidos a los mariscos, a menudo comparado con cangrejo o langosta. Mejor cortado grueso y sellado en una sartén muy caliente con mantequilla. La clave es extraer la humedad primero para lograr una costra dorada.",
      lookalikes: ['Hericium coralloides', 'Hericium americanum'],
      imageUrl: 'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=400',
    },
    {
      slug: 'shiitake',
      commonName: 'Shiitake',
      scientificName: 'Lentinula edodes',
      family: 'Marasmiaceae',
      order: 'Agaricales',
      type: 'edible',
      difficulty: 'intermediate',
      substrate: ['hardwood sawdust', 'oak logs'],
      colonizationWeeksMin: 8,
      colonizationWeeksMax: 52,
      fruitingTempFMin: 55,
      fruitingTempFMax: 75,
      fruitingTempCMin: 13,
      fruitingTempCMax: 24,
      expectedFlushes: 10,
      biologicalEfficiency: '40–80% on logs (multi-year)',
      betaGlucanContent: 'High (lentinan)',
      indoorOutdoor: 'both',
      descriptionEn: 'Shiitake is the world\'s second most cultivated mushroom and a cornerstone of East Asian cuisine for over 1,000 years. Native to the mountains of China, Japan, and Korea, it grows naturally on decaying broadleaf trees. Its rich, smoky, umami flavor profile is unmatched in the culinary world.',
      descriptionEs: 'El Shiitake es el segundo hongo más cultivado del mundo y un pilar de la cocina del este asiático durante más de 1,000 años. Nativo de las montañas de China, Japón y Corea, crece naturalmente en árboles de hoja caduca en descomposición.',
      cultivationNotesEn: 'Shiitake on logs is a long game: inoculate oak logs in spring, allow 6–12 months for colonization, then "shock" with cold water to trigger fruiting. On supplemented sawdust blocks, colonization is 8–12 weeks. Fruiting requires cold shocking (50°F / 10°C water soak for 24 hours).',
      cultivationNotesEs: 'El Shiitake en troncos es un juego largo: inocula troncos de roble en primavera, permite 6-12 meses de colonización y luego da un "shock" con agua fría para desencadenar la fructificación.',
      medicalNotesEn: 'Contains lentinan (a beta-1,3-glucan), eritadenine (cardiovascular benefits), and AHCC. Lentinan has FDA Orphan Drug status and is used in Japan as a cancer immunotherapy adjunct. Eritadenine significantly reduces cholesterol.',
      medicalNotesEs: 'Contiene lentinan (un beta-1,3-glucano), eritadenina (beneficios cardiovasculares) y AHCC. El lentinan tiene estatus de Medicamento Huérfano de la FDA y se usa en Japón como adyuvante en inmunoterapia contra el cáncer.',
      cookingNotesEn: 'The workhorse of umami cooking. Dried shiitake is even more intense than fresh. Remove the tough stems (save for stock). Sauté in sesame oil, use in ramen broth, stir-fries, duxelles, or risotto. The key compound lentinan is more bioavailable when cooked.',
      cookingNotesEs: 'El caballo de batalla de la cocina umami. El Shiitake deshidratado es aún más intenso que el fresco. Retira los tallos duros (guárdalos para caldo). Saltea en aceite de sésamo, úsalo en caldo de ramen, salteados, duxelles o risotto.',
      lookalikes: [],
      imageUrl: 'https://images.unsplash.com/photo-1585155784229-aff921ccfa12?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1585155784229-aff921ccfa12?w=400',
    },
    {
      slug: 'reishi',
      commonName: 'Reishi',
      scientificName: 'Ganoderma lucidum',
      family: 'Ganodermataceae',
      order: 'Polyporales',
      type: 'medicinal',
      difficulty: 'advanced',
      substrate: ['hardwood logs', 'hardwood stumps'],
      colonizationWeeksMin: 12,
      colonizationWeeksMax: 16,
      fruitingTempFMin: 70,
      fruitingTempFMax: 80,
      fruitingTempCMin: 21,
      fruitingTempCMax: 27,
      expectedFlushes: 1,
      biologicalEfficiency: '5–10% (antler form) / 15–20% (cap form)',
      betaGlucanContent: 'Extremely High (triterpenoids + beta-glucans)',
      indoorOutdoor: 'both',
      descriptionEn: 'Reishi — the "Mushroom of Immortality" — has been revered in Chinese medicine for over 2,000 years. Its lacquered, woody fruiting body is unmistakable: kidney-shaped with a shiny red-orange surface. Not edible raw due to extreme bitterness from triterpenoids, but consumed as a tincture or powder, it is one of the most studied medicinal fungi on Earth.',
      descriptionEs: 'El Reishi — el "Hongo de la Inmortalidad" — ha sido venerado en la medicina china durante más de 2,000 años. Su cuerpo fructificante lacado y leñoso es inconfundible: con forma de riñón y superficie brillante rojo-naranja. No es comestible crudo debido a la extrema amargura de los triterpenoides.',
      cultivationNotesEn: 'Reishi is the most demanding cultivated species. It requires a long colonization at warm temperatures (75–80°F), high CO2 during colonization, then fresh air during fruiting. The antler/coral form grows under high CO2; the classic cap form requires good FAE. Frequently grown in bags or on logs.',
      cultivationNotesEs: 'El Reishi es la especie cultivada más exigente. Requiere una larga colonización a temperaturas cálidas (24-27°C), alto CO2 durante la colonización y luego aire fresco durante la fructificación.',
      medicalNotesEn: 'Contains over 400 bioactive compounds including triterpenoids (ganoderic acids), polysaccharides, and immunomodulating proteins. Clinical evidence supports: immune enhancement, anti-tumor activity, adaptogen effects, blood pressure reduction, liver protection, and anti-anxiety. The most clinically researched medicinal mushroom globally.',
      medicalNotesEs: 'Contiene más de 400 compuestos bioactivos incluyendo triterpenoides (ácidos ganodéricos), polisacáridos y proteínas inmunomoduladoras. La evidencia clínica respalda: mejora inmune, actividad antitumoral, efectos adaptógenos, reducción de presión arterial y protección hepática.',
      cookingNotesEn: 'Not consumed as food due to extreme bitterness and tough woody texture. Best extracted as a dual-extract tincture (hot water + alcohol) to capture both beta-glucans and triterpenoids. Also available as powder for coffee, tea, or smoothies.',
      cookingNotesEs: 'No se consume como alimento debido a la extrema amargura y textura leñosa dura. Se extrae mejor como tintura de doble extracción (agua caliente + alcohol) para capturar tanto beta-glucanos como triterpenoides.',
      lookalikes: ['Ganoderma applanatum', 'Ganoderma tsugae'],
      imageUrl: 'https://images.unsplash.com/photo-1504470695779-75300268aa0e?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1504470695779-75300268aa0e?w=400',
    },
    {
      slug: 'turkey-tail',
      commonName: 'Turkey Tail',
      scientificName: 'Trametes versicolor',
      family: 'Polyporaceae',
      order: 'Polyporales',
      type: 'medicinal',
      difficulty: 'intermediate',
      substrate: ['hardwood logs', 'hardwood stumps', 'hardwood sawdust'],
      colonizationWeeksMin: 4,
      colonizationWeeksMax: 8,
      fruitingTempFMin: 50,
      fruitingTempFMax: 75,
      fruitingTempCMin: 10,
      fruitingTempCMax: 24,
      expectedFlushes: 2,
      biologicalEfficiency: '10–15%',
      betaGlucanContent: 'Very High (PSK, PSP)',
      indoorOutdoor: 'both',
      descriptionEn: "Turkey Tail is one of the most studied medicinal mushrooms on Earth, named for its colorful concentric rings that mirror a wild turkey's tail feathers. Found on fallen logs across every forested continent, Trametes versicolor contains PSK (polysaccharide-K) and PSP (polysaccharide peptide) — two of the most researched immunomodulatory compounds in oncology. Not a culinary mushroom, but a powerful medicinal ally.",
      descriptionEs: "La Cola de Pavo es uno de los hongos medicinales más estudiados del planeta, nombrado por sus coloridos anillos concéntricos que imitan las plumas de la cola de un pavo salvaje. Encontrado en troncos caídos en todos los continentes forestados, Trametes versicolor contiene PSK y PSP — dos de los compuestos inmunomoduladores más investigados en oncología.",
      cultivationNotesEn: "Turkey Tail grows naturally on dead hardwood and is moderately easy to cultivate. Inoculate oak, maple, or alder logs with plug spawn and allow 4–8 weeks for colonization outdoors. On sterilized sawdust blocks, colonization is faster (3–5 weeks). It does not require aggressive FAE or humidity control compared to other species.",
      cultivationNotesEs: "La Cola de Pavo crece naturalmente en madera dura muerta y es moderadamente fácil de cultivar. Inocula troncos de roble, arce o aliso con spawn en tacos y permite 4-8 semanas de colonización en exteriores. En bloques de aserrín esterilizado, la colonización es más rápida (3-5 semanas).",
      medicalNotesEn: "PSK (krestin) is approved in Japan and China as a cancer immunotherapy adjunct and has been used clinically since the 1970s. Multiple randomized controlled trials demonstrate improved survival rates in gastric, colorectal, breast, and lung cancers when used alongside chemotherapy. Also shows strong antiviral properties and HPV clearance in clinical studies.",
      medicalNotesEs: "El PSK (krestin) está aprobado en Japón y China como adyuvante de inmunoterapia contra el cáncer y se ha usado clínicamente desde los años 70. Múltiples ensayos clínicos demuestran tasas de supervivencia mejoradas en cánceres gástrico, colorrectal, de mama y pulmón cuando se usa junto a quimioterapia.",
      cookingNotesEn: "Not consumed as food — the fruiting body is tough and leathery. Best prepared as a decoction (simmered 20–30 min) or dual-extract tincture (hot water + alcohol). The tea has a pleasant, earthy, slightly sweet flavor. Also available as a powder to blend into coffee or smoothies.",
      cookingNotesEs: "No se consume como alimento — el cuerpo fructificante es duro y coriáceo. Se prepara mejor como decocción (hervida 20-30 min) o tintura de doble extracción. El té tiene un sabor agradable, terroso y ligeramente dulce. También disponible en polvo para mezclar en café o batidos.",
      lookalikes: ['Stereum ostrea (False Turkey Tail)', 'Trametes hirsuta'],
      imageUrl: '',
      thumbnailUrl: '',
    },
    {
      slug: 'maitake',
      commonName: 'Maitake',
      scientificName: 'Grifola frondosa',
      family: 'Meripilaceae',
      order: 'Polyporales',
      type: 'medicinal',
      difficulty: 'advanced',
      substrate: ['hardwood logs', 'oak stumps', 'supplemented hardwood sawdust'],
      colonizationWeeksMin: 12,
      colonizationWeeksMax: 20,
      fruitingTempFMin: 50,
      fruitingTempFMax: 65,
      fruitingTempCMin: 10,
      fruitingTempCMax: 18,
      expectedFlushes: 1,
      biologicalEfficiency: '20–30%',
      betaGlucanContent: 'Extremely High (D-fraction)',
      indoorOutdoor: 'both',
      descriptionEn: "Maitake — the \"dancing mushroom\" in Japanese — is a prized culinary and medicinal powerhouse. Its overlapping, ruffled fronds grow in massive clusters at the base of oak trees, resembling a hen on a nest (hence its other name, Hen of the Woods). Wild specimens can weigh over 50 lbs. Its D-fraction beta-glucan is among the most potent immunomodulatory compounds ever isolated from a fungus.",
      descriptionEs: "Maitake — el \"hongo danzante\" en japonés — es un poderoso hongo culinario y medicinal. Sus frondas rizada y superpuestas crecen en grandes racimos en la base de robles, pareciendo una gallina en su nido (de ahí su nombre en inglés, Hen of the Woods). Los especímenes silvestres pueden pesar más de 20 kg.",
      cultivationNotesEn: "Maitake is one of the most challenging species to cultivate. It requires extended colonization on supplemented hardwood (12–20 weeks), cold shock fruiting (40–50°F / 4–10°C), and very high relative humidity. Outdoors, inoculate oak stumps in fall for natural fruiting the following autumn. Commercial indoor cultivation requires precise environmental control.",
      cultivationNotesEs: "El Maitake es una de las especies más difíciles de cultivar. Requiere colonización extendida en madera dura suplementada (12-20 semanas), fructificación con shock frío (4-10°C) y humedad relativa muy alta. En exteriores, inocula tocones de roble en otoño para una fructificación natural el otoño siguiente.",
      medicalNotesEn: "Maitake D-fraction is a unique beta-1,3/1,6-glucan with demonstrated anti-tumor activity and immune potentiation. Clinical studies show significant immune response in cancer patients as an adjunct therapy. Also strongly researched for blood sugar regulation (activates insulin receptors independently), PCOS management, and metabolic syndrome. One of the few mushrooms with published human clinical trials.",
      medicalNotesEs: "La D-fracción del Maitake es un beta-1,3/1,6-glucano único con actividad antitumoral demostrada y potenciación inmune. Estudios clínicos muestran respuesta inmune significativa en pacientes con cáncer como terapia adyuvante. También investigado para regulación del azúcar en sangre, manejo de SOP y síndrome metabólico.",
      cookingNotesEn: "Outstanding culinary mushroom with a rich, woodsy, deep umami flavor. The ruffled fronds have a satisfying chewy-crisp texture when cooked at high heat. Best roasted whole at high temperature, sautéed in butter with soy sauce and ginger, or used in risotto, pasta, and soups. The fronds naturally pull apart into meaty pieces.",
      cookingNotesEs: "Hongo culinario excepcional con un rico sabor umami profundo y ahumado. Las frondas rizadas tienen una textura satisfactoriamente masticable y crujiente cuando se cocinan a fuego alto. Mejor asado entero a temperatura alta, salteado en mantequilla con salsa de soya y jengibre, o usado en risotto, pasta y sopas.",
      lookalikes: ['Meripilus sumstinei (Black-Staining Polypore)', 'Bondarzewia berkeleyi'],
      imageUrl: '',
      thumbnailUrl: '',
    },
  ]

  for (const s of speciesData) {
    await prisma.species.upsert({
      where: { slug: s.slug },
      update: s,
      create: s,
    })
    console.log(`  ✓ Species: ${s.commonName}`)
  }

  // ── PRODUCTS ──────────────────────────────────────────────────────────────
  const blueOysterSpecies = await prisma.species.findUnique({ where: { slug: 'blue-oyster' } })
  const lionsMaineSpecies = await prisma.species.findUnique({ where: { slug: 'lions-mane' } })
  const shiitakeSpecies = await prisma.species.findUnique({ where: { slug: 'shiitake' } })
  const reishiSpecies = await prisma.species.findUnique({ where: { slug: 'reishi' } })

  const productsData = [
    {
      slug: 'blue-oyster-grain-spawn',
      nameEn: 'Blue Oyster Grain Spawn',
      nameEs: 'Spawn de Grano Ostra Azul',
      descriptionEn: 'Premium Blue Oyster grain spawn on sterilized rye berries. Lab-tested for contamination, certified organic, and ready to inoculate any hardwood substrate.',
      descriptionEs: 'Spawn de grano premium de Ostra Azul en bayas de centeno esterilizadas. Probado en laboratorio para contaminación, certificado orgánico y listo para inocular cualquier sustrato de madera dura.',
      category: 'spawn',
      subcategory: 'grain-spawn',
      speciesId: blueOysterSpecies?.id,
      price: 1499,
      compareAtPrice: 1999,
      images: ['https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=800'],
      isOrganic: true,
      inStock: true,
      tags: ['beginner', 'oyster', 'grain-spawn', 'organic'],
      specsDifficulty: 'beginner',
      specsColonizationTime: '2–3 weeks',
      specsFruitingTempF: '55–65°F',
      specsFruitingTempC: '13–18°C',
      specsIdealSubstrate: 'Hardwood sawdust, straw',
      specsExpectedYield: '1–3 flushes',
      specsIndoorOutdoor: 'both',
    },
    {
      slug: 'lions-mane-fruiting-block',
      nameEn: "Lion's Mane Fruiting Block",
      nameEs: 'Bloque Fructificante Melena de León',
      descriptionEn: 'Ready-to-fruit Lion\'s Mane block on supplemented hardwood. Fully colonized in our sterile lab — just open and mist to see the iconic white pompom in 1–2 weeks.',
      descriptionEs: 'Bloque de Melena de León listo para fructificar en madera dura suplementada. Completamente colonizado en nuestro laboratorio estéril — solo abre y rocía para ver el icónico pompón blanco en 1-2 semanas.',
      category: 'kit',
      subcategory: 'fruiting-block',
      speciesId: lionsMaineSpecies?.id,
      price: 3499,
      compareAtPrice: null,
      images: ['https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=800'],
      isOrganic: true,
      inStock: true,
      tags: ['medicinal', 'lions-mane', 'kit', 'ready-to-fruit'],
      specsDifficulty: 'intermediate',
      specsColonizationTime: 'Already colonized',
      specsFruitingTempF: '65–75°F',
      specsFruitingTempC: '18–24°C',
      specsIdealSubstrate: 'Supplemented hardwood (included)',
      specsExpectedYield: '1–2 flushes, 200–400g',
      specsIndoorOutdoor: 'indoor',
    },
    {
      slug: 'beginners-grow-kit-bundle',
      nameEn: "Beginner's Complete Grow Kit",
      nameEs: 'Kit de Cultivo Completo para Principiantes',
      descriptionEn: 'Everything you need to grow your first mushrooms: Blue Oyster grain spawn, one sterilized substrate bag, a humidity dome, a misting bottle, and our 30-page Beginner\'s Grow Guide.',
      descriptionEs: 'Todo lo que necesitas para cultivar tus primeros hongos: spawn de grano Ostra Azul, una bolsa de sustrato esterilizado, una cúpula de humedad, un atomizador y nuestra Guía del Principiante de 30 páginas.',
      category: 'bundle',
      subcategory: 'beginner-bundle',
      speciesId: blueOysterSpecies?.id,
      price: 4999,
      compareAtPrice: 6999,
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
      isOrganic: true,
      inStock: true,
      tags: ['beginner', 'bundle', 'kit', 'best-seller'],
      specsDifficulty: 'beginner',
      specsColonizationTime: '2–3 weeks',
      specsFruitingTempF: '55–65°F',
      specsFruitingTempC: '13–18°C',
      specsIdealSubstrate: 'Included (sterilized hardwood)',
      specsExpectedYield: '1–3 flushes, 150–300g each',
      specsIndoorOutdoor: 'indoor',
    },
    {
      slug: 'shiitake-log-kit',
      nameEn: 'Shiitake Log Inoculation Kit',
      nameEs: 'Kit de Inoculación de Tronco Shiitake',
      descriptionEn: 'Grow Shiitake the traditional way on oak logs. Includes plug spawn, wax, drill bit template, and the complete log inoculation guide. One kit inoculates 2–3 logs and produces mushrooms for 3–5 years.',
      descriptionEs: 'Cultiva Shiitake de la manera tradicional en troncos de roble. Incluye spawn en tacos, cera, plantilla para taladro y la guía completa de inoculación de troncos. Un kit inocula 2-3 troncos y produce hongos durante 3-5 años.',
      category: 'kit',
      subcategory: 'log-kit',
      speciesId: shiitakeSpecies?.id,
      price: 2999,
      compareAtPrice: null,
      images: ['https://images.unsplash.com/photo-1585155784229-aff921ccfa12?w=800'],
      isOrganic: true,
      inStock: true,
      tags: ['shiitake', 'outdoor', 'log-cultivation', 'traditional'],
      specsDifficulty: 'intermediate',
      specsColonizationTime: '6–12 months on logs',
      specsFruitingTempF: '55–75°F',
      specsFruitingTempC: '13–24°C',
      specsIdealSubstrate: 'Oak logs (not included)',
      specsExpectedYield: 'Multiple flushes over 3–5 years',
      specsIndoorOutdoor: 'outdoor',
    },
    {
      slug: 'reishi-dual-extract-tincture',
      nameEn: 'Reishi Dual-Extract Tincture',
      nameEs: 'Tintura de Doble Extracción de Reishi',
      descriptionEn: '2oz dual-extract tincture made from organic Ganoderma lucidum fruiting bodies. Hot water + alcohol extraction captures the full spectrum of triterpenoids and beta-glucans. 50:1 concentration ratio.',
      descriptionEs: 'Tintura de doble extracción de 60ml hecha de cuerpos fructificantes orgánicos de Ganoderma lucidum. La extracción con agua caliente + alcohol captura el espectro completo de triterpenoides y beta-glucanos. Concentración 50:1.',
      category: 'wellness',
      subcategory: 'tinctures',
      speciesId: null,
      price: 3999,
      compareAtPrice: null,
      images: ['https://images.unsplash.com/photo-1504470695779-75300268aa0e?w=800'],
      isOrganic: true,
      inStock: true,
      tags: ['reishi', 'wellness', 'tincture', 'medicinal', 'adaptogen'],
      specsDifficulty: null,
      specsColonizationTime: null,
      specsFruitingTempF: null,
      specsFruitingTempC: null,
      specsIdealSubstrate: null,
      specsExpectedYield: null,
      specsIndoorOutdoor: null,
    },
    // ── Liquid Culture Syringes ────────────────────────────────────────────
    {
      slug: 'lions-mane-liquid-culture',
      nameEn: "Lion's Mane Liquid Culture Syringe",
      nameEs: 'Jeringa de Cultivo Líquido Melena de León',
      descriptionEn: 'shrooms Culture Bank — 10cc live Hericium erinaceus mycelium. Lab-isolated, colonizes grain in 5–10 days. Includes 16G needle and alcohol swab.',
      descriptionEs: 'shrooms Culture Bank — 10cc de micelio vivo de Hericium erinaceus. Coloniza en 5–10 días. Incluye aguja 16G y swab de alcohol.',
      category: 'spawn', subcategory: 'liquid-culture',
      speciesId: lionsMaineSpecies?.id,
      price: 1799, compareAtPrice: null,
      images: ['https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=800'],
      isOrganic: true, inStock: true,
      tags: ['medicinal', 'liquid-culture', 'lions-mane'],
      specsDifficulty: 'intermediate', specsColonizationTime: '5–10 days',
      specsFruitingTempF: '65–75°F', specsFruitingTempC: '18–24°C',
      specsIdealSubstrate: 'Supplemented hardwood sawdust',
      specsExpectedYield: '200–400g per flush', specsIndoorOutdoor: 'indoor',
    },
    {
      slug: 'blue-oyster-liquid-culture',
      nameEn: 'Blue Oyster Liquid Culture Syringe',
      nameEs: 'Jeringa de Cultivo Líquido Ostra Azul',
      descriptionEn: 'shrooms Culture Bank — 10cc live Pleurotus ostreatus mycelium. Lab-isolated, colonizes grain in 5–10 days. Includes 16G needle and alcohol swab.',
      descriptionEs: 'shrooms Culture Bank — 10cc de micelio vivo de Pleurotus ostreatus. Coloniza en 5–10 días. Incluye aguja 16G y swab de alcohol.',
      category: 'spawn', subcategory: 'liquid-culture',
      speciesId: blueOysterSpecies?.id,
      price: 1799, compareAtPrice: null,
      images: ['https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=800'],
      isOrganic: true, inStock: true,
      tags: ['beginner', 'liquid-culture', 'oyster'],
      specsDifficulty: 'beginner', specsColonizationTime: '5–10 days',
      specsFruitingTempF: '55–65°F', specsFruitingTempC: '13–18°C',
      specsIdealSubstrate: 'Hardwood sawdust, straw',
      specsExpectedYield: '1–3 flushes, 25% BE', specsIndoorOutdoor: 'both',
    },
    {
      slug: 'reishi-liquid-culture',
      nameEn: 'Reishi Liquid Culture Syringe',
      nameEs: 'Jeringa de Cultivo Líquido Reishi',
      descriptionEn: 'shrooms Culture Bank — 10cc live Ganoderma lucidum mycelium. Lab-isolated, colonizes grain in 5–10 days. Includes 16G needle and alcohol swab.',
      descriptionEs: 'shrooms Culture Bank — 10cc de micelio vivo de Ganoderma lucidum. Coloniza en 5–10 días. Incluye aguja 16G y swab de alcohol.',
      category: 'spawn', subcategory: 'liquid-culture',
      speciesId: reishiSpecies?.id,
      price: 1799, compareAtPrice: null,
      images: ['https://images.unsplash.com/photo-1504470695779-75300268aa0e?w=800'],
      isOrganic: true, inStock: true,
      tags: ['medicinal', 'liquid-culture', 'reishi'],
      specsDifficulty: 'advanced', specsColonizationTime: '5–10 days (on grain)',
      specsFruitingTempF: '70–80°F', specsFruitingTempC: '21–27°C',
      specsIdealSubstrate: 'Hardwood logs or sawdust',
      specsExpectedYield: '1 flush (medicinal)', specsIndoorOutdoor: 'both',
    },
    {
      slug: 'shiitake-liquid-culture',
      nameEn: 'Shiitake Liquid Culture Syringe',
      nameEs: 'Jeringa de Cultivo Líquido Shiitake',
      descriptionEn: 'shrooms Culture Bank — 10cc live Lentinula edodes mycelium. Lab-isolated, colonizes grain in 5–10 days. Includes 16G needle and alcohol swab.',
      descriptionEs: 'shrooms Culture Bank — 10cc de micelio vivo de Lentinula edodes. Coloniza en 5–10 días. Incluye aguja 16G y swab de alcohol.',
      category: 'spawn', subcategory: 'liquid-culture',
      speciesId: shiitakeSpecies?.id,
      price: 1799, compareAtPrice: null,
      images: ['https://images.unsplash.com/photo-1585155784229-aff921ccfa12?w=800'],
      isOrganic: true, inStock: true,
      tags: ['edible', 'liquid-culture', 'shiitake'],
      specsDifficulty: 'intermediate', specsColonizationTime: '5–10 days (on grain)',
      specsFruitingTempF: '55–75°F', specsFruitingTempC: '13–24°C',
      specsIdealSubstrate: 'Hardwood sawdust or oak logs',
      specsExpectedYield: 'Multiple flushes', specsIndoorOutdoor: 'both',
    },
  ]

  for (const p of productsData) {
    const { speciesId, ...productFields } = p
    const created = await prisma.product.upsert({
      where: { slug: p.slug },
      update: { ...productFields, speciesId: speciesId ?? undefined },
      create: { ...productFields, speciesId: speciesId ?? undefined },
    })

    // Create a default variant
    await prisma.productVariant.upsert({
      where: { sku: `${p.slug}-default` },
      update: {},
      create: {
        productId: created.id,
        name: 'Standard',
        price: p.price,
        stock: 50,
        sku: `${p.slug}-default`,
      },
    })

    console.log(`  ✓ Product: ${p.nameEn}`)
  }

  console.log('\n🍄 Seed complete!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
