import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🍄 Seeding DirtyShrooms database...')

  // ── SPECIES ───────────────────────────────────────────────────────────────
  const speciesData = [
    {
      slug: 'blue-oyster',
      commonName: 'Blue Oyster',
      scientificName: 'Pleurotus ostreatus',
      family: 'Pleurotaceae',
      order: 'Agaricales',
      type: 'edible',
      difficulty: 'beginner',
      substrate: ['hardwood sawdust', 'straw', 'coffee grounds'],
      colonizationWeeksMin: 2,
      colonizationWeeksMax: 3,
      fruitingTempFMin: 55,
      fruitingTempFMax: 65,
      fruitingTempCMin: 13,
      fruitingTempCMax: 18,
      expectedFlushes: 3,
      biologicalEfficiency: '25%',
      betaGlucanContent: 'High (25–30% dry weight)',
      indoorOutdoor: 'both',
      descriptionEn: 'The Blue Oyster mushroom is the most forgiving species for beginners. Native to temperate forests worldwide, Pleurotus ostreatus forms beautiful fan-shaped clusters with a blue-grey to cream coloring that deepens in cooler temperatures. It has a mild, slightly sweet flavor with a firm, meaty texture that works wonderfully across many cooking styles.',
      descriptionEs: 'El hongo Ostra Azul es la especie más indulgente para principiantes. Nativo de bosques templados de todo el mundo, el Pleurotus ostreatus forma hermosos racimos en forma de abanico con una coloración azul-gris a crema que se profundiza en temperaturas más frías. Tiene un sabor suave y ligeramente dulce con una textura firme y carnosa.',
      cultivationNotesEn: 'Blue Oysters thrive in a wide range of conditions. Pack your substrate into buckets or bags, inoculate with grain spawn, and wait 2–3 weeks for full colonization. Induce fruiting by introducing fresh air exchange and maintaining 85–95% humidity. Expect 3–4 flushes over 6–8 weeks.',
      cultivationNotesEs: 'Las Ostras Azules prosperan en una amplia gama de condiciones. Empaca el sustrato en cubetas o bolsas, inocula con spawn de grano y espera 2-3 semanas para la colonización completa. Induce la fructificación introduciendo intercambio de aire fresco y manteniendo 85-95% de humedad.',
      medicalNotesEn: 'Rich in beta-glucans, ergothioneine, and lovastatin. Studies suggest cholesterol-lowering effects, immune modulation, and anti-inflammatory properties. High in protein (30% dry weight) and contains all essential amino acids.',
      medicalNotesEs: 'Rico en beta-glucanos, ergotionina y lovastatina. Los estudios sugieren efectos reductores del colesterol, modulación inmune y propiedades antiinflamatorias. Alto en proteínas (30% peso seco) y contiene todos los aminoácidos esenciales.',
      cookingNotesEn: 'Excellent sautéed in butter with garlic, roasted in the oven, or used as a seafood substitute in tacos and stir-fries. The firm texture holds up well to high heat. Pairs beautifully with thyme, white wine, and cream.',
      cookingNotesEs: 'Excelente salteado en mantequilla con ajo, asado al horno o usado como sustituto de mariscos en tacos y salteados. La textura firme aguanta bien el calor alto. Combina perfecto con tomillo, vino blanco y crema.',
      lookalikes: [],
      imageUrl: 'https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=400',
    },
    {
      slug: 'lions-mane',
      commonName: "Lion's Mane",
      scientificName: 'Hericium erinaceus',
      family: 'Hericiaceae',
      order: 'Russulales',
      type: 'medicinal',
      difficulty: 'intermediate',
      substrate: ['hardwood sawdust'],
      colonizationWeeksMin: 3,
      colonizationWeeksMax: 4,
      fruitingTempFMin: 65,
      fruitingTempFMax: 75,
      fruitingTempCMin: 18,
      fruitingTempCMax: 24,
      expectedFlushes: 2,
      biologicalEfficiency: '15–20%',
      betaGlucanContent: 'Very High',
      indoorOutdoor: 'indoor',
      descriptionEn: "Lion's Mane is one of the most visually striking and scientifically fascinating mushrooms in existence. Its cascading white spines resemble a lion's mane, giving it an otherworldly appearance. Revered in Traditional Chinese Medicine for centuries, modern science has confirmed powerful neuroprotective and cognitive-enhancing properties.",
      descriptionEs: "La Melena de León es uno de los hongos más visualmente impactantes y científicamente fascinantes que existen. Sus espinas blancas en cascada se asemejan a la melena de un león, dándole una apariencia de otro mundo. Venerada en la medicina tradicional china durante siglos, la ciencia moderna ha confirmado poderosas propiedades neuroprotectoras.",
      cultivationNotesEn: "Lion's Mane requires high humidity (90–95%) and excellent fresh air exchange. It is sensitive to CO2 buildup, which causes it to form elongated, icicle-like growths instead of the classic pom-pom shape. Use enriched hardwood sawdust blocks and maintain 65–75°F during fruiting.",
      cultivationNotesEs: "La Melena de León requiere alta humedad (90-95%) y excelente intercambio de aire fresco. Es sensible a la acumulación de CO2, que la hace formar crecimientos elongados en forma de carámbano en lugar de la forma clásica de pompón.",
      medicalNotesEn: "Contains hericenones and erinacines — two unique compounds that stimulate Nerve Growth Factor (NGF) synthesis. Clinical studies show improvement in mild cognitive impairment, anxiety, depression, and neuropathic pain. Currently being researched for Alzheimer's and Parkinson's prevention.",
      medicalNotesEs: "Contiene hericenones y erinacinas — dos compuestos únicos que estimulan la síntesis del Factor de Crecimiento Nervioso (NGF). Estudios clínicos muestran mejoras en deterioro cognitivo leve, ansiedad, depresión y dolor neuropático.",
      cookingNotesEn: "Has a remarkable seafood-like texture and flavor — often compared to crab or lobster. Best sliced thick and seared in a very hot pan with butter. The key is extracting moisture first to achieve a golden crust. Superb in pasta, risotto, or simply on toast.",
      cookingNotesEs: "Tiene una textura y sabor notablemente parecidos a los mariscos, a menudo comparado con cangrejo o langosta. Mejor cortado grueso y sellado en una sartén muy caliente con mantequilla. La clave es extraer la humedad primero para lograr una costra dorada.",
      lookalikes: ['Hericium coralloides', 'Hericium americanum'],
      imageUrl: 'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=400',
    },
    {
      slug: 'shiitake',
      commonName: 'Shiitake',
      scientificName: 'Lentinula edodes',
      family: 'Marasmiaceae',
      order: 'Agaricales',
      type: 'edible',
      difficulty: 'intermediate',
      substrate: ['hardwood sawdust', 'oak logs'],
      colonizationWeeksMin: 8,
      colonizationWeeksMax: 52,
      fruitingTempFMin: 55,
      fruitingTempFMax: 75,
      fruitingTempCMin: 13,
      fruitingTempCMax: 24,
      expectedFlushes: 10,
      biologicalEfficiency: '40–80% on logs (multi-year)',
      betaGlucanContent: 'High (lentinan)',
      indoorOutdoor: 'both',
      descriptionEn: 'Shiitake is the world\'s second most cultivated mushroom and a cornerstone of East Asian cuisine for over 1,000 years. Native to the mountains of China, Japan, and Korea, it grows naturally on decaying broadleaf trees. Its rich, smoky, umami flavor profile is unmatched in the culinary world.',
      descriptionEs: 'El Shiitake es el segundo hongo más cultivado del mundo y un pilar de la cocina del este asiático durante más de 1,000 años. Nativo de las montañas de China, Japón y Corea, crece naturalmente en árboles de hoja caduca en descomposición.',
      cultivationNotesEn: 'Shiitake on logs is a long game: inoculate oak logs in spring, allow 6–12 months for colonization, then "shock" with cold water to trigger fruiting. On supplemented sawdust blocks, colonization is 8–12 weeks. Fruiting requires cold shocking (50°F / 10°C water soak for 24 hours).',
      cultivationNotesEs: 'El Shiitake en troncos es un juego largo: inocula troncos de roble en primavera, permite 6-12 meses de colonización y luego da un "shock" con agua fría para desencadenar la fructificación.',
      medicalNotesEn: 'Contains lentinan (a beta-1,3-glucan), eritadenine (cardiovascular benefits), and AHCC. Lentinan has FDA Orphan Drug status and is used in Japan as a cancer immunotherapy adjunct. Eritadenine significantly reduces cholesterol.',
      medicalNotesEs: 'Contiene lentinan (un beta-1,3-glucano), eritadenina (beneficios cardiovasculares) y AHCC. El lentinan tiene estatus de Medicamento Huérfano de la FDA y se usa en Japón como adyuvante en inmunoterapia contra el cáncer.',
      cookingNotesEn: 'The workhorse of umami cooking. Dried shiitake is even more intense than fresh. Remove the tough stems (save for stock). Sauté in sesame oil, use in ramen broth, stir-fries, duxelles, or risotto. The key compound lentinan is more bioavailable when cooked.',
      cookingNotesEs: 'El caballo de batalla de la cocina umami. El Shiitake deshidratado es aún más intenso que el fresco. Retira los tallos duros (guárdalos para caldo). Saltea en aceite de sésamo, úsalo en caldo de ramen, salteados, duxelles o risotto.',
      lookalikes: [],
      imageUrl: 'https://images.unsplash.com/photo-1585155784229-aff921ccfa12?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1585155784229-aff921ccfa12?w=400',
    },
    {
      slug: 'reishi',
      commonName: 'Reishi',
      scientificName: 'Ganoderma lucidum',
      family: 'Ganodermataceae',
      order: 'Polyporales',
      type: 'medicinal',
      difficulty: 'advanced',
      substrate: ['hardwood logs', 'hardwood stumps'],
      colonizationWeeksMin: 12,
      colonizationWeeksMax: 16,
      fruitingTempFMin: 70,
      fruitingTempFMax: 80,
      fruitingTempCMin: 21,
      fruitingTempCMax: 27,
      expectedFlushes: 1,
      biologicalEfficiency: '5–10% (antler form) / 15–20% (cap form)',
      betaGlucanContent: 'Extremely High (triterpenoids + beta-glucans)',
      indoorOutdoor: 'both',
      descriptionEn: 'Reishi — the "Mushroom of Immortality" — has been revered in Chinese medicine for over 2,000 years. Its lacquered, woody fruiting body is unmistakable: kidney-shaped with a shiny red-orange surface. Not edible raw due to extreme bitterness from triterpenoids, but consumed as a tincture or powder, it is one of the most studied medicinal fungi on Earth.',
      descriptionEs: 'El Reishi — el "Hongo de la Inmortalidad" — ha sido venerado en la medicina china durante más de 2,000 años. Su cuerpo fructificante lacado y leñoso es inconfundible: con forma de riñón y superficie brillante rojo-naranja. No es comestible crudo debido a la extrema amargura de los triterpenoides.',
      cultivationNotesEn: 'Reishi is the most demanding cultivated species. It requires a long colonization at warm temperatures (75–80°F), high CO2 during colonization, then fresh air during fruiting. The antler/coral form grows under high CO2; the classic cap form requires good FAE. Frequently grown in bags or on logs.',
      cultivationNotesEs: 'El Reishi es la especie cultivada más exigente. Requiere una larga colonización a temperaturas cálidas (24-27°C), alto CO2 durante la colonización y luego aire fresco durante la fructificación.',
      medicalNotesEn: 'Contains over 400 bioactive compounds including triterpenoids (ganoderic acids), polysaccharides, and immunomodulating proteins. Clinical evidence supports: immune enhancement, anti-tumor activity, adaptogen effects, blood pressure reduction, liver protection, and anti-anxiety. The most clinically researched medicinal mushroom globally.',
      medicalNotesEs: 'Contiene más de 400 compuestos bioactivos incluyendo triterpenoides (ácidos ganodéricos), polisacáridos y proteínas inmunomoduladoras. La evidencia clínica respalda: mejora inmune, actividad antitumoral, efectos adaptógenos, reducción de presión arterial y protección hepática.',
      cookingNotesEn: 'Not consumed as food due to extreme bitterness and tough woody texture. Best extracted as a dual-extract tincture (hot water + alcohol) to capture both beta-glucans and triterpenoids. Also available as powder for coffee, tea, or smoothies.',
      cookingNotesEs: 'No se consume como alimento debido a la extrema amargura y textura leñosa dura. Se extrae mejor como tintura de doble extracción (agua caliente + alcohol) para capturar tanto beta-glucanos como triterpenoides.',
      lookalikes: ['Ganoderma applanatum', 'Ganoderma tsugae'],
      imageUrl: 'https://images.unsplash.com/photo-1504470695779-75300268aa0e?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1504470695779-75300268aa0e?w=400',
    },
    {
      slug: 'wine-cap',
      commonName: 'Wine Cap',
      scientificName: 'Stropharia rugosoannulata',
      family: 'Strophariaceae',
      order: 'Agaricales',
      type: 'edible',
      difficulty: 'beginner',
      substrate: ['wood chips', 'straw', 'garden beds'],
      colonizationWeeksMin: 4,
      colonizationWeeksMax: 6,
      fruitingTempFMin: 50,
      fruitingTempFMax: 70,
      fruitingTempCMin: 10,
      fruitingTempCMax: 21,
      expectedFlushes: 99,
      biologicalEfficiency: 'Very high — perennial in garden beds',
      betaGlucanContent: 'Moderate',
      indoorOutdoor: 'outdoor',
      descriptionEn: "The Wine Cap — also called the King Stropharia or Garden Giant — is outdoor cultivation at its most effortless. Sprinkle spawn on wood chips, water occasionally, and harvest burgundy-capped mushrooms for years. It integrates perfectly into permaculture food forests, builds soil, and can produce impressive harvests with almost no intervention.",
      descriptionEs: "El Vino Cap — también llamado King Stropharia o Gigante de Jardín — es el cultivo exterior en su forma más sencilla. Esparce spawn en astillas de madera, riega ocasionalmente y cosecha hongos con cabezas borgoña durante años. Se integra perfectamente en jardines de permacultura, construye suelo y puede producir cosechas impresionantes con casi ninguna intervención.",
      cultivationNotesEn: "Broadcast spawn over a 4–6 inch layer of wood chips (or straw) in a shaded garden area. Keep moist during dry periods. No sterilization needed. The mycelium will spread through the wood chips and fruit prolifically in spring and fall when temperatures drop below 70°F. Can produce for 5+ years from a single inoculation.",
      cultivationNotesEs: "Esparce spawn sobre una capa de 10-15 cm de astillas de madera (o paja) en un área sombreada del jardín. Mantén húmedo en períodos secos. No se necesita esterilización. El micelio se extenderá por las astillas y fructificará prolíficamente en primavera y otoño.",
      medicalNotesEn: "Rich in ergothioneine and beta-glucans. Contains good levels of B vitamins including B12 precursors. Known for its role in soil bioremediation — the mycelium breaks down wood and concentrates nutrients, improving garden soil structure significantly.",
      medicalNotesEs: "Rico en ergotionina y beta-glucanos. Contiene buenos niveles de vitaminas B incluyendo precursores de B12. Conocido por su papel en la biorremediación del suelo — el micelio descompone la madera y concentra nutrientes, mejorando significativamente la estructura del suelo del jardín.",
      cookingNotesEn: "Mild flavor with a slight earthiness and nuttiness when young. The button stage (cap still closed) is most prized for texture. Larger, open caps have a more intense, almost wine-like flavor. Excellent sautéed, grilled whole, in omelets, or sliced thin on pizza. Handle gently — they bruise easily.",
      cookingNotesEs: "Sabor suave con un ligero terroso y nuez cuando son jóvenes. La etapa de botón (sombrero aún cerrado) es la más apreciada por la textura. Los sombreros más grandes y abiertos tienen un sabor más intenso, casi a vino.",
      lookalikes: ['Cortinarius (deadly Webcaps)', 'Amanita rubescens'],
      imageUrl: 'https://images.unsplash.com/photo-1541904031027-00d5c22f7cf2?w=800',
      thumbnailUrl: 'https://images.unsplash.com/photo-1541904031027-00d5c22f7cf2?w=400',
    },
  ]

  for (const s of speciesData) {
    await prisma.species.upsert({
      where: { slug: s.slug },
      update: s,
      create: s,
    })
    console.log(`  ✓ Species: ${s.commonName}`)
  }

  // ── PRODUCTS ──────────────────────────────────────────────────────────────
  const blueOysterSpecies = await prisma.species.findUnique({ where: { slug: 'blue-oyster' } })
  const lionsMaineSpecies = await prisma.species.findUnique({ where: { slug: 'lions-mane' } })
  const shiitakeSpecies = await prisma.species.findUnique({ where: { slug: 'shiitake' } })

  const productsData = [
    {
      slug: 'blue-oyster-grain-spawn',
      nameEn: 'Blue Oyster Grain Spawn',
      nameEs: 'Spawn de Grano Ostra Azul',
      descriptionEn: 'Premium Blue Oyster grain spawn on sterilized rye berries. Lab-tested for contamination, certified organic, and ready to inoculate any hardwood substrate.',
      descriptionEs: 'Spawn de grano premium de Ostra Azul en bayas de centeno esterilizadas. Probado en laboratorio para contaminación, certificado orgánico y listo para inocular cualquier sustrato de madera dura.',
      category: 'spawn',
      subcategory: 'grain-spawn',
      speciesId: blueOysterSpecies?.id,
      price: 1499,
      compareAtPrice: 1999,
      images: ['https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=800'],
      isOrganic: true,
      inStock: true,
      tags: ['beginner', 'oyster', 'grain-spawn', 'organic'],
      specsDifficulty: 'beginner',
      specsColonizationTime: '2–3 weeks',
      specsFruitingTempF: '55–65°F',
      specsFruitingTempC: '13–18°C',
      specsIdealSubstrate: 'Hardwood sawdust, straw',
      specsExpectedYield: '1–3 flushes',
      specsIndoorOutdoor: 'both',
    },
    {
      slug: 'lions-mane-fruiting-block',
      nameEn: "Lion's Mane Fruiting Block",
      nameEs: 'Bloque Fructificante Melena de León',
      descriptionEn: 'Ready-to-fruit Lion\'s Mane block on supplemented hardwood. Fully colonized in our sterile lab — just open and mist to see the iconic white pompom in 1–2 weeks.',
      descriptionEs: 'Bloque de Melena de León listo para fructificar en madera dura suplementada. Completamente colonizado en nuestro laboratorio estéril — solo abre y rocía para ver el icónico pompón blanco en 1-2 semanas.',
      category: 'kit',
      subcategory: 'fruiting-block',
      speciesId: lionsMaineSpecies?.id,
      price: 3499,
      compareAtPrice: null,
      images: ['https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=800'],
      isOrganic: true,
      inStock: true,
      tags: ['medicinal', 'lions-mane', 'kit', 'ready-to-fruit'],
      specsDifficulty: 'intermediate',
      specsColonizationTime: 'Already colonized',
      specsFruitingTempF: '65–75°F',
      specsFruitingTempC: '18–24°C',
      specsIdealSubstrate: 'Supplemented hardwood (included)',
      specsExpectedYield: '1–2 flushes, 200–400g',
      specsIndoorOutdoor: 'indoor',
    },
    {
      slug: 'beginners-grow-kit-bundle',
      nameEn: "Beginner's Complete Grow Kit",
      nameEs: 'Kit de Cultivo Completo para Principiantes',
      descriptionEn: 'Everything you need to grow your first mushrooms: Blue Oyster grain spawn, one sterilized substrate bag, a humidity dome, a misting bottle, and our 30-page Beginner\'s Grow Guide.',
      descriptionEs: 'Todo lo que necesitas para cultivar tus primeros hongos: spawn de grano Ostra Azul, una bolsa de sustrato esterilizado, una cúpula de humedad, un atomizador y nuestra Guía del Principiante de 30 páginas.',
      category: 'bundle',
      subcategory: 'beginner-bundle',
      speciesId: blueOysterSpecies?.id,
      price: 4999,
      compareAtPrice: 6999,
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
      isOrganic: true,
      inStock: true,
      tags: ['beginner', 'bundle', 'kit', 'best-seller'],
      specsDifficulty: 'beginner',
      specsColonizationTime: '2–3 weeks',
      specsFruitingTempF: '55–65°F',
      specsFruitingTempC: '13–18°C',
      specsIdealSubstrate: 'Included (sterilized hardwood)',
      specsExpectedYield: '1–3 flushes, 150–300g each',
      specsIndoorOutdoor: 'indoor',
    },
    {
      slug: 'shiitake-log-kit',
      nameEn: 'Shiitake Log Inoculation Kit',
      nameEs: 'Kit de Inoculación de Tronco Shiitake',
      descriptionEn: 'Grow Shiitake the traditional way on oak logs. Includes plug spawn, wax, drill bit template, and the complete log inoculation guide. One kit inoculates 2–3 logs and produces mushrooms for 3–5 years.',
      descriptionEs: 'Cultiva Shiitake de la manera tradicional en troncos de roble. Incluye spawn en tacos, cera, plantilla para taladro y la guía completa de inoculación de troncos. Un kit inocula 2-3 troncos y produce hongos durante 3-5 años.',
      category: 'kit',
      subcategory: 'log-kit',
      speciesId: shiitakeSpecies?.id,
      price: 2999,
      compareAtPrice: null,
      images: ['https://images.unsplash.com/photo-1585155784229-aff921ccfa12?w=800'],
      isOrganic: true,
      inStock: true,
      tags: ['shiitake', 'outdoor', 'log-cultivation', 'traditional'],
      specsDifficulty: 'intermediate',
      specsColonizationTime: '6–12 months on logs',
      specsFruitingTempF: '55–75°F',
      specsFruitingTempC: '13–24°C',
      specsIdealSubstrate: 'Oak logs (not included)',
      specsExpectedYield: 'Multiple flushes over 3–5 years',
      specsIndoorOutdoor: 'outdoor',
    },
    {
      slug: 'reishi-dual-extract-tincture',
      nameEn: 'Reishi Dual-Extract Tincture',
      nameEs: 'Tintura de Doble Extracción de Reishi',
      descriptionEn: '2oz dual-extract tincture made from organic Ganoderma lucidum fruiting bodies. Hot water + alcohol extraction captures the full spectrum of triterpenoids and beta-glucans. 50:1 concentration ratio.',
      descriptionEs: 'Tintura de doble extracción de 60ml hecha de cuerpos fructificantes orgánicos de Ganoderma lucidum. La extracción con agua caliente + alcohol captura el espectro completo de triterpenoides y beta-glucanos. Concentración 50:1.',
      category: 'wellness',
      subcategory: 'tinctures',
      speciesId: null,
      price: 3999,
      compareAtPrice: null,
      images: ['https://images.unsplash.com/photo-1504470695779-75300268aa0e?w=800'],
      isOrganic: true,
      inStock: true,
      tags: ['reishi', 'wellness', 'tincture', 'medicinal', 'adaptogen'],
      specsDifficulty: null,
      specsColonizationTime: null,
      specsFruitingTempF: null,
      specsFruitingTempC: null,
      specsIdealSubstrate: null,
      specsExpectedYield: null,
      specsIndoorOutdoor: null,
    },
  ]

  for (const p of productsData) {
    const { speciesId, ...productFields } = p
    const created = await prisma.product.upsert({
      where: { slug: p.slug },
      update: { ...productFields, speciesId: speciesId ?? undefined },
      create: { ...productFields, speciesId: speciesId ?? undefined },
    })

    // Create a default variant
    await prisma.productVariant.upsert({
      where: { sku: `${p.slug}-default` },
      update: {},
      create: {
        productId: created.id,
        name: 'Standard',
        price: p.price,
        stock: 50,
        sku: `${p.slug}-default`,
      },
    })

    console.log(`  ✓ Product: ${p.nameEn}`)
  }

  console.log('\n🍄 Seed complete!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
